### ISSUE TITLE
masas.fm/api/play/?time_interval_id=1 not working

### ISSUE THREAD

**Issue by tbinetruy** [MASASFM/masas#25]
### Bug:

Nothing happens clicking on play on discover page for #EarlyMorning, #LateAfternoon, and #LateEvening. The console show error:

<img width="634" alt="error console" src="https://cloud.githubusercontent.com/assets/19936648/17462894/20af60a2-5cbb-11e6-80cb-4d26e1aea23f.png">
<img width="437" alt="request headers" src="https://cloud.githubusercontent.com/assets/19936648/17462895/20b59e36-5cbb-11e6-988c-4e0e4afbc754.png">
<img width="438" alt="response headers" src="https://cloud.githubusercontent.com/assets/19936648/17462896/20b90ae4-5cbb-11e6-9947-c809534900f4.png">
### How to reproduce bug:

Go to Discover page and click on the empty artwork on the middle the page for #EarlyMorning (switch with slider).
### What should happen:

When you click on the empty artwork for #EarlyMorning, the server should respond with a song of type timeInterval = 1.
### Comments:

This bug only happens on #EarlyMorning (timeInterval = 1). However, the /api/ page shows that there are songs of type timeInterval 1 that exist (eg: http://www.masas.fm/api/songs/48/).

**Comment by tbinetruy** [comment]
Happens with #LateAfternoon too (timeInterval = 4) after I listened to it all day. I think the problem occurs when all songs from a given timeInterval have been played the same (positive) amount of time.

**Comment by jpic** [comment]
Thanks !!

Fixed by 109e682e59d5e92e1175d0af25efc9f8e9642688
