### ISSUE TITLE
Discover/popular algorithm update

### ISSUE THREAD

**Issue by tbinetruy** [MASASFM/masas#28]
Bellow is how the algo will work for the pages Discover and Popular.
### Discover

The goal of discover is 2 fold:
- Help artists uploading songs have their songs reach as many people as possible
- Help listeners discover new songs

The Discover is divided in 6 sections, namely: #EarlyMorning, #LateMorning, #EarlyAfternoon, #LateAfternoon, #EarlyEvening, #LateEvening (#names subject to change).

When an artist uploads a song, she selects one of the 6 hashtags above.
When a user goes on Discover, he selects which of the 6 above hashtags he wants to discover songs from. On each song, he can like it, skip it, report it as spam or as copyright infringement.

Users need to be logged in to be able to listen to music from the Discover section. 
### Popular

The popular section's goal is 3 fold:
- Allow artists that have aggregated a good ranking (based on likes/play ratio most likely) on songs to have their songs get even more visibility by being in popular
- Allow listeners, not necessarily logged in the website, to click play and have a popular song play
- Mimic a radio where Popular is a playlist running all day long with each hashtag (mentioned above) playlist starting at a given local time each day. By local time, we mean that if #EarlyAfternoon is scheduled to start at 4pm each day, then it will in Japan and in the US (as opposed to it starting at 4pm UTC for instance)
### Out

A song's ranking can make it such that the song no longer plays in Discover and Popular. 
### Implementation

Each uploaded song can be in 1 of the 3 following categories:
-in discover
-in popular
-out (songs not in discover nor popular)
A song can also be both in discover and popular.

Each uploaded song goes directly in the Discover pool until it is moved to another pool (out or popular).

Each uploaded song will remain in the Discover pool for a minimum of 2 weeks (14 days). After which, if this song is ranked in the bottom 10% of the the Discover pool, it is removed from the Discover pool into the Out pool. A song is not removed from Discover until it is ranked in the bottom 10%

Moreover, a playlist of popular songs will be generated each day based on the ranking of songs in the Discover pool. The top 20 songs/30% of each timeInterval in Discover will be playing on Popular the next day.

**Comment by jpic** [comment]
Can you proceed to splitting that one in small issues please ? Thanks !!
On Aug 9, 2016 12:43 PM, "Thomas Binétruy-Pic" notifications@github.com
wrote:

Assigned #28 https://github.com/MASASFM/masas/issues/28 to @jpic
https://github.com/jpic.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
https://github.com/MASASFM/masas/issues/28#event-749663676, or mute the
thread
