### ISSUE TITLE
error on patching user nested fields on /api/users/[user_id]/

### ISSUE THREAD

**Issue by tbinetruy** [MASASFM/masas#29]
### Problem

Patching on /api/users/[user_id]/ is not possible for some fields including:
- city
- link_set
### How to reproduce

Go on /api/users/[user_id]/ when logged in as superuser or [user_id] on DRF interface. Click on Raw Data form bellow the JSON and submit the following JSON by clicking PATCH:
`{"link_set": ["hi"]}`
`{"city": "NYC"}`
will return both return 
`{
    "link_set": [
        {
            "non_field_errors": [
                "Invalid data. Expected a dictionary, but got unicode."
            ]
        }
    ]
}`

However, patching name and occupation fields work:
`{ "name": "thomas"}`
returns
`{
    "url": "http://localhost:8000/api/users/3/",
    "username": "test",
    "email": "t@tt.tt",
    "name": "thomas",
    "city": null,
    "occupation": "heyo",
    "avatar_url": null,
    "link_set": [],
    "songs": [],
    "likes": [],
    "dislikes": [],
    "usersteps": []
}`
and 
`{ "occupation": "slacker" }`
returns
`{
    "url": "http://localhost:8000/api/users/3/",
    "username": "test",
    "email": "t@tt.tt",
    "name": "thomas",
    "city": null,
    "occupation": "slacker",
    "avatar_url": null,
    "link_set": [],
    "songs": [],
    "likes": [],
    "dislikes": [],
    "usersteps": []
}`
### What is needed

The possibility to patch **link_set** and **city** on /api/user/[user_id] by [user_id] when [user_id] is logged in. As of right now, the edit profile page tries to patch **link_set** with an array of strings and **city** with a string

**Comment by jpic** [comment]
Hey bro ! I deployed a couple of fixes, not the best of the world but the best I can do given I'm on hollidays with your nephews, check out the commit messages for details. Hope this helps, see ya soon !
