### ISSUE TITLE
---URGENT--- Play/pause/play PROBLEM on Mobile

### ISSUE THREAD

**Issue by vbinetruy** [MASASFM/masas#3]
The music won't play unless the song is paused and played again. The problem arises for each songs; e.g. I'm listening to music on my phone from MASAS but when I get to the end of a song, the next song won't play automatically, I have to pause it and press play again...

**The bug was found on:**

-iPhone (5s, 6, 6s, 6sPlus)
-Safari (Chrome won't allow Facebook sign-in),
-MASAS.fm.

-Android (LG G4)
-Chrome 
-MASAS.fm,

**Comment by tbinetruy** [comment]
When you press play, a script asks for a song on the MASAS servers and then retrieves it from the SC servers and then plays the song. Mobile platforms do not allow scripts to play songs (think annoying adds that randomly play songs). 

I'm looking into simulating a click with a JS click object. however, this will only work if the mobile browsers don't look for a physical touch from the screen (and thus require both a JS click object and a touch feedback at the OS level for the sound to play)

**Comment by mickamasas** [comment]
Does the problem will be resolved when we will push on the Play and Apple stores? If so that's a fake problem, if not have we tried "play automatically" sounds when we're on a page ? If it bugs once, when the user push the button the second times it might work?

**Comment by vbinetruy** [comment]
That is overly complicated. It's simple, the music has to play when the user presses on the play button (on the first try!)

**Comment by tbinetruy** [comment]
Problem solved.
