### ISSUE TITLE
Need filter on /api/cities/

### ISSUE THREAD

**Issue by tbinetruy** [MASASFM/masas#30]
### Issue

Currently on /api/cities/, there is no way to filter by field "search_name".
### How to reproduce

Go on /api/cities/, there is no filter icon on DRF UI (neither when logged in)
### What is needed

A way to request JSON on /api/cities/ filtered by "search_name". This will allow me to implement autocomplete from the edit profile UI.

**Comment by jpic** [comment]
http://www.masas.fm/api/cities/?q=paris%20france
​
https://github.com/yourlabs/django-cities-light/blob/stable/3.x.x/cities_light/contrib/restframework3.py#L98-L115
Not perfect, but might do for now.
