### ISSUE TITLE
Cities api not working

### ISSUE THREAD

**Issue by tbinetruy** [MASASFM/masas#33]
Cities API not working making the autocomplete bug in profile editing:
http://www.masas.fm/api/cities/

**Comment by jpic** [comment]
Define "not working"​.

**Comment by tbinetruy** [comment]
My bad. The cities are unavailable from /api/play [1]. I believe it's because the new database hasn't been populated with Django Cities Light city/country data. Indeed, the DB pointing to masas.fm is empty (as opposed to the one pointing to dev2).

[1] http://www.masas.fm/api/cities/
