### ISSUE TITLE
Change masas.fm Google search description

### ISSUE THREAD

**Issue by vbinetruy** [MASASFM/masas#44]
At the moment, when MASAS is searched (and found) on Google, the description under the name and the URL is uninformative bullshit ;)

Here is what it Should be changed to (for now):

--> MASAS - "Make A Sound And Share"... A new way of Discovering music, one that gives all Artists an equal chance of getting Discovered! 

<img width="645" alt="screen shot 2016-10-11 at 1 03 12 pm" src="https://cloud.githubusercontent.com/assets/19936607/19307518/971f00f2-9083-11e6-8cb0-cca158a22788.png">

**Comment by mickamasas** [comment]
MASAS - Make A Sound And Share
What discover new music should feel like. No bias, no commercials and all for free.

More marketing and catchy what do you think?

**Comment by mickamasas** [comment]
Any comment? This is critical
