### ISSUE TITLE
Log-in through Mobile website

### ISSUE THREAD

**Issue by vbinetruy** [MASASFM/masas#5]
When you arrive on MASAS.fm (on your mobile) you arrive on a Homepage (1st image) that does not give you the ability to log-in. The page has a top bar that says "Login" but it isn't a button.

<img width="229" alt="screen shot 2016-06-16 at 3 11 49 pm" src="https://cloud.githubusercontent.com/assets/19936607/16129874/ad63db78-33d4-11e6-87b7-3c3c41ec3703.png">

The user has to expand the side-menu and press on the very little "Log-In" button at the bottom right.

<img width="218" alt="screen shot 2016-06-16 at 3 13 18 pm" src="https://cloud.githubusercontent.com/assets/19936607/16129920/eb5c0e46-33d4-11e6-9cb7-62faf33da4b9.png">

 He then arrives on the same Homepage as described above, but this time, the Homepage has a button to Log-In.

<img width="273" alt="screen shot 2016-06-16 at 3 11 38 pm" src="https://cloud.githubusercontent.com/assets/19936607/16129877/af75f31a-33d4-11e6-8ccb-b282625d8ca3.png">

I think that it was originally done so that we could have the MASAS logo and slogan on the landing page. We can still have it this way, we just need to make the "Login" word on the top bar of the Homepage an actual button that redirects to a Facebook Log-In. 

**What has to be done:**

-Delete the 2nd screen (Second Homepage, with big grey login button).
-Make the word "Login" on the top bar of the Homepage a Facebook log-in button
-Delete "Home" in the side-menu
-Make the Homepage (landing page) come from "Log-in" in the side-menu

**Comment by tbinetruy** [comment]
I'm not deleting the Home page. Indeed, we need it. Because otherwise, you can't be logged in, go to whatever page and come back to the home page without logging off. What is there to do on the homepage ? Not much. But that's where we have the description of the website (when you click on the bubble bellow the logo).

I'll fix the rest for now. Micka needs to update the zeplin so it reflects it.

**Comment by mickamasas** [comment]
That's a major issue, if people can't be logged in, they can't use MASAS at all.
On my side Zeplin seems to be on date, I've this screenshot for the Home page on Zeplin, check yours if it don't appear.

PS : "Request an invitation" should be changed with "Continue as "Facebook Name"" when we have such cookies ;)

<img width="322" alt="capture d ecran 2016-06-21 a 7 05 16 pm" src="https://cloud.githubusercontent.com/assets/20041868/16238999/26d9382e-37e3-11e6-8e07-a8c0f9e5e929.png">

**Comment by jpic** [comment]
Same here !

Not sure if we can use the facebook name before the user has given permission to do so though.

**Comment by vbinetruy** [comment]
Micka, what you have posted is for the App! You don't have that much space on the mobile browser!

And for the login button, we can't have it in grey like that, it has to follow the facebook guidelines...It has to be properly branded. (We also have to do it for the websites (dektop) version)

**Micka** Thomas is gonna need updates for that on the Zeplin please.

https://www.facebookbrand.com/#
