### ISSUE TITLE
request for api endpoint incrementing total play count for a given song

### ISSUE THREAD

**Issue by tbinetruy** [MASASFM/masas#50]
hi,

I'm looking for an api endpoint that increments total_play_count for a given song.

This endpoint should be public. indeed, we're looking to increment songs played from anonymous users (users that are not logged into masas but that are listening to songs). This end point would also be if a user listens to a song from another user's profile or from his likes. 

Indeed, currently, the API only provides a 'play_count' field for each song that reflects on how many times a connected user has listened to a song from the Discover page. This entry is important for ranking songs in the Popular section that will be shortly implemented and thus is still needed. Hence the need for another song field called 'total_play_count' that would be incremented anytime a song is played (from a logged in user or not, and from the discover page or not).

Thanks,

Thomas

**Comment by mickamasas** [comment]
Hi,

Good point, there is my though:

We could, from a API point of view, take into account the plays from unlogged users from an account that display "log in" button but is in reality MASAS account. Just need to preset every time a user is unlogged make MASAS account as a default account.

What do you think?

Micka

**Comment by tbinetruy** [comment]
Not a bad idea. So you're suggesting we make an Anonymous user account for users that aren't logged in right ? And by anonymous, I mean a user account called Anonymous in the database.

James, what do you think ?
