### ISSUE TITLE
Mobile website might not be working (not loading for me)!

### ISSUE THREAD

**Issue by vbinetruy** [MASASFM/masas#52]
I don't know if it just me (maybe because of the network in Dubai or my iPhone 5s with the latest iOS) but the website is not loading (on both Safari and Chrome). The loading bar on both browsers fills up completely within 5 seconds but the page stays completely blank. 

Could you check on your phone if MASAS.FM works, please.

UPDATE

It is loading in (Chrome) incognito on my phone. The only problem is that I MASAS does not work on Chrome (for iPhone) and I do not know how to clear the cache on Safari (iPhone).

**Comment by vbinetruy** [comment]
I was just having the same problem on my laptop (Mac, Chrome). 

I tried loading it in Incognito AND IT WORKED.

Is it because of the cache? 

Did someone recently (in the last 2 hours) push an update?

How long does the cache last for MASAS.fm? We'll every (returning) users have to clear their cache (for MASAS) in order not to see a blank page? 

My worry is that most users won't know that it is due to the cache and that they have to clear it.

**Comment by tbinetruy** [comment]
I think this bug was related to Paperjs not working on Chrome 55 (importSVG method not working, see: https://github.com/paperjs/paper.js/issues/1222).

I have updated Paperjs and the website now works on all devices.
