### ISSUE TITLE
Discovery Slider TIP

### ISSUE THREAD

**Issue by vbinetruy** [MASASFM/masas#53]
It isn't a major issue (and one that you shouldn't waste time fixing if it'll take too long) but the Discovery Slider TIP (Drag the sun around!) shows up every-time you go to another page and come back to Discover (even when you have already moved it around and even when you are logged in)

**Comment by tbinetruy** [comment]
Very good point. And very annoying to.

Should we remove it all together ? Since we now have the 'drag the sun around' caption where the hastag usually goes.
