### ISSUE TITLE
Interface for letting users log in is unbearable

### ISSUE THREAD

**Issue by tbinetruy** [MASASFM/masas#6]
I would like to improve the interface on: http://www.masas.fm/api/usersteps/
Currently, all the users are listed in the user field a dropdown, I'd like to improve this.

How should we handle that ? Can we modify the REST api page ? Or would that be easier to do just with the django admin page ? Or should I create a new page allowing for that ? Or should you using a django template (since that page would not need to be part or the single page app) ?

**Comment by jpic** [comment]
Let me understand correctly: you want to add the "Can log in" userstep to a new user ?

You are authenticated as an administrator, and open the API page here: http://www.masas.fm/api/usersteps/

In the form at the bottom, you have to:
- select the user,
- select "Can log in",
- click "POST",

So, how would a better process look like to you ?

**Comment by tbinetruy** [comment]
The problem the user selection. all the users are shown when you select user step 2. So you can’t know which users already have user step 2. So if there are 100 users and 50 of them already have a user step 2, you’d like the drop down to only show the 50 users that do not already have user step 2. I don’t know if we can modify the way the api page is. 

we’d need something easier. For instance when the user step dropdown has ‘can log in’ selected, ideally, the user dropdown would filter out the users that already have user step 2 such that only the users that don’t have that user step are shown in the user dropdown. I forgot my admin passwd, so look into that actual admin interface see if it’s already possible through it.

if we can’t do that, then maybe i should create a page for that. or if its quicker, maybe you can create a page server side (aka through a django template since this page would not need to be part of the SPA).

**Comment by tbinetruy** [comment]
Le besoin c’est que c’est ca rend le travail extrêmement désagréable pour celui qui est en charge d’inviter les utilisateurs. D’où le terme ‘unbearable’. L’implementation marche. La UX pour l’admin est juste atroce. Il faudrait trouver un moyen de la rendre plus sympa sans y passer 10 heures. Avec la UI tel quel, l’admin peut se planter assez facilement. Essaye, va sur la page /api/usersteps et compte combien de temps il te faut pour mettre un userstep 2 a un user qui ne l’a pas. bonne chance. et là, on n’a pas beaucoup de user. La perte de temps et la possibilité de se planter dans la manie croira exponentiellement avec le nombre de user à gerer.

Aussi, c’est pas moi que tu aides en faisant ca. C’est nous: victor micka, toi et moi. 


bises


et bonne chance pour ton scaling sur l’autre site ;)

**Comment by jpic** [comment]
Perhaps we could automatically let them in, and just disable the "active" option on users we don't want in ?

![2016-06-24-024055_527x69_scrot](https://cloud.githubusercontent.com/assets/94636/16324530/8c7d08d0-39b5-11e6-9c09-e2474f02f9d5.png)

The con is that it opens the door to potentialy malicious users, the pro is that our friends won't have to wait to join or invite their friends !

**Comment by vbinetruy** [comment]
The best would be to have two lists of users in the interface. The ones that have not yet been accepted and the ones that have been accepted. The cherry on top would be to have a little button next to each user to either accept or deny them.

**Comment by jpic** [comment]
While I can see the cost of implementing this, I fail to understand the value.

**Comment by jpic** [comment]
Ok, we can add the active checkbox in the user list column.

**Comment by vbinetruy** [comment]
The point is, right now, I can't quickly see which user has the permission to use the platform completely and which don't. Furthermore, I can't easily (within seconds) give permission to many users.

**Comment by jpic** [comment]
Hence my proposal to auto-accept​ by default !

I would love not to have to take any manual action when I invite a friend.

**Comment by jpic** [comment]
Fixed the interface.
![2016-06-24-183521_197x293_scrot](https://cloud.githubusercontent.com/assets/94636/16344055/e85caed2-3a3a-11e6-9810-475b4d1c8a4f.png)

See /admin/MASAS/user/
