### ISSUE TITLE
Music stops when computer' screen saving begins 

### ISSUE THREAD

**Issue by mickamasas** [MASASFM/masas#62]
Saw it on mac for now. Try to put 1mn screen saving - music will stop automatically. Play any other music platform, this will never appear.

**Comment by vbinetruy** [comment]
I set my screen saver to 1 minute and the music kept on playing. Not only that, but it also played the next song at the end. Are you sure that you're computer has a screen saver and doesn't just go to sleep? If it goes to sleep, it's completely normal that the music stops playing.
