### ISSUE TITLE
Logo / Favicon Redesign

### ISSUE THREAD

**Issue by vbinetruy** [MASASFM/masas#7]
The logo is amazing! (on Apple products)*

We have to fix this because on most people's laptops and phones (because most people do not have high-end tech like we do) the logo doesn't look great at all. The logo looks great when it is big and the colors on the screen are crystal clear, but it quickly starts looking like shit when we make it smaller (favicon). Furthermore, people are having the hardest differentiating the MASAS logo on the stickers from the Volkswagen logo.

The logo is eventually going to have to be re-designed (as we / if we ever, get big) because of all these issues. So we might as well do it now.

My idea was just to remove the inner bar at the right of the M.

![new logo](https://cloud.githubusercontent.com/assets/19936607/16236501/9e2a3afa-37a6-11e6-81fa-48eb5e7b8b40.png)

**Comment by mickamasas** [comment]
Netflix had a huge problem about their logo, they change it yesterday to be better on mobile. Netflix have been created in 1997, they have more than 5.5 Billions incomes today. Did they though it was a major issue? We can change details as often as we wanted but we need to release, release often and start iterating on real sprints not such details..

**Comment by jpic** [comment]
Don't worry about the logo, it's awesome :guitar:
