### ISSUE TITLE
blur in Popular

### ISSUE THREAD

**Issue by mickamasas** [MASASFM/masas#78]
No need of blur in Popular section

**Comment by vbinetruy** [comment]
We're trying something different with the Crowdradio for now. We need it to be somewhat different than the Discover section. So for now, we're keeping it blurred, deleting the title, and only showing one cover photo at a time on the screen (deleting the covers of past sounds that form a line at the left. 

The plan is to test that out for a couple of days, see how it looks, and then, we'll make changes (if needed).

We're trying to differentiate the Crowdradio (visually) as much as possible from Discover. Give something new to look at (to the user); making two distinctively different features.
