### ISSUE TITLE
Share the sound I make

### ISSUE THREAD

**Issue by jpic** [MASASFM/masas#8]
Currently, as a logged in user, I can not find my own songs on [/upload](http://www.masas.fm/upload), I do find some songs I like though. 

To open the beta, we need to have to share the sounds we make if I'm not mistaken :)

I'd like to add [a few songs](https://soundcloud.com/james-lebowski), perhaps somebody could like them and upload them meanwhile ? My friend François Van Hessen who did the arrangements for [reggea vegetarien]()

Not sure at what time of the day these should be, dunno how it'd mix with all the electronic music we've got so far, the experiment seems interresting to have, perhaps we could have a hangouts about this ? Also I hope you guys will be in Bretagne this summer, so we could perhaps make a bit of sound :saxophone: 

Thanks :guitar:

**Comment by vbinetruy** [comment]
All we are doing right now is a small private beta. We are just adding a few hundred songs to the system  for a few users to test out our algorithms. As soon as we are done with that, (August) we will start the Public Beta on which you will only be able to upload your own songs (not your likes). But we have a few things to finish before that (likes page, profile settings, favicon, play pause play problem, mobile-login, the I Certify Page, algorithms (I don't like, report as spam, Discover, Popular), the Report Copyright infringement... Basically, a lot!

Congratulations!!! Your sound is now on MASAS!!! :)

And Yes, We'll be in Britanny this summer :)
