### ISSUE TITLE
[UX] Skip the welcoming screen

### ISSUE THREAD

**Issue by mickamasas** [MASASFM/masas#89]
-Skip the Welcoming screen
-Go directly to the Crowdradio page

**Comment by tbinetruy** [comment]
I'm not sure what you mean ? That's how it is on both mobile and desktop.

Currently, it goes from a 3s black screen with the masas logo centered. This page fade away after 2-3s and goes straight to the crowdradio page when you're on the url: http://masas.fm


Please provide screen shots or more details regarding your request :)

**Comment by vbinetruy** [comment]
I think that Micka probably had cash problem! Delete your MASAS.fm cache from your browser (or wait 24 hours). If you don't, everything will be buggy, misplaced...

**Comment by mickamasas** [comment]
All good, it was the browser cache

Can’t wait to have the notifications bars :)
