### ISSUE TITLE
[UI]

### ISSUE THREAD

**Issue by mickamasas** [MASASFM/masas#90]
header is buggy on chrome 15' when user is unlogged
<img width="580" alt="screen shot 2017-05-08 at 2 46 54 pm" src="https://cloud.githubusercontent.com/assets/20041868/25826838/3f927e40-33fd-11e7-89c5-2a0f102673e5.png">

**Comment by mickamasas** [comment]
even if after login

**Comment by tbinetruy** [comment]
Working fine on Windows 10, Version 57.0.2987.133 (64-bit) and on my macos Sierra (all updates) mbpr 2013 with latest chrome which i can't 

<img width="960" alt="header_not_buggy" src="https://cloud.githubusercontent.com/assets/19936648/25843275/2aacde8a-34a7-11e7-8ea4-c7a1904678df.png">

<img width="945" alt="header_not_buggy_2" src="https://cloud.githubusercontent.com/assets/19936648/25843486/c2c3bc16-34a7-11e7-968d-25aa68198262.PNG">

The Chrome 15 you mention is quite a few versions outdated. 


Please try reloading your page by clearing the cache: ctrl+shift+r or loading the website in incognito mode and let me know if the problem persists.


I'm also needed the version of your chrome browser (menu -> about chrome) and your results on you're OS' default browser (Edge or Safari) for comparaison. 


Cheers

P.S. The second screenshot is me verfiying that the problem doesn't come from screen > 13 inch
